### ISSUE TITLE
can not use rviz in docker

### ISSUE THREAD

**Issue by LongruiDong** [johannes-graeter/limo#67]
Hi~

after build the docker, when I setp to
```
rviz -d ${your_catkin_workspace}/src/demo_keyframe_bundle_adjustment_meta/res/default.rviz

```

returns:

```
root@76323bdb623b:/workspace/limo_ws# rviz -d src/limo/demo_keyframe_bundle_adjustment_meta/res/default.rviz                                                       
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.
```

How could view rviz window with docker?

**Comment by johannes-graeter** [comment]
oh yeah thats a tricky one. You need to share the X server of the docker container as described here https://medium.com/intro-to-artificial-intelligence/rviz-on-docker-bdf4d0fca5b

**Comment by LongruiDong** [comment]
> 

I am quite new to docker, is there simpler way by modifing docker-compose only?

after reading that blog and [this](https://www.cloudsavvyit.com/10520/how-to-run-gui-applications-in-a-docker-container/) , what I understand:
below is docker-compose.yml
```
version: '3.4'

services:
  limo:
    container_name: limo
    build:
      context: ./src
    image: ros:melodic-perception
    ports:
      - 8888:8888
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - $HOME/Project/limo/limo_data:/limo_data 
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    stdin_open: true
    tty: true
```

**Comment by LongruiDong** [comment]
> > 
> 
> I am quite new to docker, is there simpler way by modifing docker-compose only?
> 
> after reading that blog and [this](https://www.cloudsavvyit.com/10520/how-to-run-gui-applications-in-a-docker-container/) , what I understand: below is docker-compose.yml
> 
> ```
> version: '3.4'
> 
> services:
>   limo:
>     container_name: limo
>     build:
>       context: ./src
>     image: ros:melodic-perception
>     ports:
>       - 8888:8888
>     environment:
>       - DISPLAY=${DISPLAY}
>     volumes:
>       - $HOME/Project/limo/limo_data:/limo_data 
>       - /tmp/.X11-unix:/tmp/.X11-unix
>     network_mode: host
>     stdin_open: true
>     tty: true
> ```

lucky!

I change docker-compose.yml like this:
```
version: '3.4'

services:
  limo:
    container_name: limo
    build:
      context: ./src
    image: ros:melodic-perception
    ports:
      - 8888:8888
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - $HOME/limo_data:/limo_data 
      - /tmp/.X11-unix:/tmp/.X11-unix
    # network_mode: host #  error: conflicting options: host type networking can't be used with links comment to avoid it
    stdin_open: true
    tty: true

```
rebuild and I can invoke rviz normally
